config/routes.rb
Rails.application.routes.draw do

  resources :booklist

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/booklist_controller.rb
class BooklistController < ApplicationController
  def index
  	@booklist = Book.all
  end

  def show 
 	@book = Book.find(params[:id])  
  end

  def new 
    @book = Book.new 
  end

  def edit 
  	@book = Book.find(params[:id])
  end

  def create 
    @book = Book.create(book_params)
    if @book.save #this is a boolean. true if it succeed. false if message fails to save
      redirect_to booklist_index_path
    else
      render :new #render stays on the current HTTP request
  	end
  end

  def update 
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to booklist_index_path
  end

  def destroy 
    Book.find(params[:id]).destroy
    redirect_to booklist_index_path
  end

  private

  def book_params
   	params.require(:book).permit(:name, :author)
  end
     
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booklist_helper.rb
module BooklistHelper
end

app/views/booklist/edit.html.erb
<h1>Edit Book</h1>

<%= form_for @book, url: booklist_path do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Back', booklist_index_path %>

app/views/booklist/index.html.erb
<h1>Booklist</h1>

<table>
<thead>
<tr>
  <th>Title</th>
  <th>Author</th>
  <th colspan="3"></th>
</tr>
</thead>

<tbody>
	<% @booklist.each do |book| %>
		<tr>
			<td><%= book.name %></td>
			<td><%= book.author %></td>
			<td><%= link_to 'Show', booklist_path(book) %></td>
    		<td><%= link_to 'Edit', edit_booklist_path(book) %></td> <!-- Edit this particular book -->
    		<td><%= link_to 'Destroy', booklist_path(book), method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>	
	<% end %>
</tbody>

</table>

<%= link_to 'Add new book', new_booklist_path %>

app/views/booklist/new.html.erb
<h1>Booklist</h1>

<%= form_for @book, url: booklist_index_path do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Back', booklist_index_path %>

app/views/booklist/show.html.erb
<h1>Show Book</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>